#### SYMFONY OVERRIDES
framework:
    cache:
        prefix_seed: '%kernel.environment%.pimcore.froq'
    session:
        enabled: true
        cookie_secure: true
        cookie_samesite: lax
        cookie_lifetime: 259200

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file