#### SYMFONY OVERRIDES
framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            redis:
                adapter: 'cache.adapter.redis'
                provider: '%env(REDIS_URL)%'
    session:
        enabled: true
        cookie_secure: true
        cookie_samesite: lax
        cookie_lifetime: 259200

youwe_pimcore_elasticsearch:
    es_hosts:
        - 'http://127.0.0.1:9200'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file