#### SYMFONY OVERRIDES
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                #tags: true
                default_lifetime: 31536000  # 1 year
                #adapter: pimcore.cache.adapter.doctrine_dbal
                #provider: 'doctrine.dbal.default_connection'
                adapter: cache.adapter.redis_tag_aware
                provider: '%env(REDIS_URL)%'
    session:
        enabled: true
        cookie_secure: true
        cookie_samesite: lax
        cookie_lifetime: 259200

youwe_pimcore_elasticsearch:
    es_hosts:
        - 'http://127.0.0.1:9200'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file