knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AZURE_SECRET_ID)%'
            redirect_route: connect_azure_check
            redirect_params: { }
            tenant: '%env(OAUTH_AZURE_TENANT_ID)%'