monolog:
    channels: [messenger_audit]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ["!event"]
                formatter: monolog.formatter.line
                include_stacktraces: true
            messenger:
                type: stream
                path: "%kernel.logs_dir%/messenger.log"
                level: debug
                channels: ["messenger_audit"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug