oneup_flysystem:
    adapters:
        public_uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME_DUMP_SQL)%'
        private_uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME_DUMP_SQL)%'
        uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME_DUMP_SQL)%'

    filesystems:
        public_uploads_filesystem:
            adapter: uploads_adapter
        private_uploads_filesystem:
            adapter: uploads_adapter
        uploads_filesystem:
            adapter: uploads_adapter
