security:
    access_decision_manager:
        strategy: unanimous
    providers:
        pimcore_admin:
            id: Pimcore\Bundle\AdminBundle\Security\User\UserProvider
        members:
            id: MembersBundle\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pimcore WebDAV HTTP basic // DO NOT CHANGE!
        pimcore_admin_webdav:
            pattern: ^/admin/asset/webdav
            provider: pimcore_admin
            http_basic: ~

        # Pimcore admin form login // DO NOT CHANGE!
        pimcore_admin:
            anonymous: ~
            pattern: ^/admin(/.*)?$
            # admin firewall is stateless as we open the admin
            # session on demand for non-blocking parallel requests
            stateless: true
            provider: pimcore_admin
            logout:
                path:   /admin/logout
                target: /admin/login
                success_handler: Pimcore\Bundle\AdminBundle\Security\LogoutSuccessHandler
            guard:
                entry_point: Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
                authenticators:
                    - Pimcore\Bundle\AdminBundle\Security\Guard\AdminAuthenticator
            two_factor:
                auth_form_path: /admin/login/2fa                   # Path or route name of the two-factor form
                check_path: /admin/login/2fa-verify                # Path or route name of the two-factor code check
                default_target_path: /admin            # Where to redirect by default after successful authentication
                always_use_default_target_path: false  # If it should always redirect to default_target_path
                auth_code_parameter_name: _auth_code   # Name of the parameter for the two-factor authentication code
                trusted_parameter_name: _trusted       # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

        portal:
            anonymous: ~
            pattern: ^/portal(/.*)?$
            provider: members
            guard:
                authenticators:
                    - Froq\PortalBundle\Security\AzureAuthenticator
            form_login:
                login_path: froq_portal.auth.login
                check_path: froq_portal.auth.login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: '%default_portal_dashboard_path%'
                always_use_default_target_path: false
            logout:
                path: froq_portal.auth.logout
                invalidate_session: false
                target: froq_portal.auth.login
            user_checker: MembersBundle\Security\UserChecker
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days

        switch:
            pattern: ^/switch
            stateless: true
            provider: members
            guard:
                authenticators:
                    - Froq\PortalBundle\Security\ApiKeyAuthenticator

        pimtoday:
            pattern: ^/pimtoday
            stateless: true
            provider: members
            guard:
                authenticators:
                    - Froq\PortalBundle\Security\PimtodayApiKeyAuthenticator

        export:
            pattern: ^/export
            stateless: true
            provider: members
            guard:
                authenticators:
                    - Froq\PortalBundle\Security\ApiKeyAuthenticator

    access_control:
        # Pimcore admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/sso/([ a-z- ]+/)?(login|logout|acs|metadata)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/settings/display-custom-logo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS}
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_PIMCORE_USER }
        - { path: ^/portal/auth/(login|login-check)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal/connect/azure, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal/connect/azure/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/portal, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/switch, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pimtoday, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        # Pimcore admin  // DO NOT CHANGE!
        ROLE_PIMCORE_ADMIN: [ROLE_PIMCORE_USER]
