froq_portal:
    resource: '@FroqPortalBundle/Controller/'
    type:     annotation
    prefix:   /portal
    trailing_slash_on_root: false

froq_portal_asset_library:
    resource: '@FroqPortalBundle/Controller/AssetLibrary/'
    type: annotation
    prefix: /portal/asset-library

froq_portal_colour_library:
    resource: '@FroqPortalBundle/ColourLibrary/Controller/'
    type: annotation
    prefix: /portal/colour-library

froq_asset:
    resource: '@FroqAssetBundle/Controller/'
    type: annotation
    prefix: /

froq_portal_switch:
    resource: '@FroqAssetBundle/Switch/Controller/'
    type:     annotation
    prefix:   /switch
    trailing_slash_on_root: false

froq_portal_pimtoday:
    resource: '@FroqAssetBundle/Pimtoday/Controller/'
    type:     annotation
    prefix:   /pimtoday
    trailing_slash_on_root: false

froq_portal_export:
    resource: '@FroqAssetBundle/Export/Controller/'
    type:     annotation
    prefix:   /export
    trailing_slash_on_root: false

froq_dashboard:
    resource: '@FroqPortalBundle/Controller/Dashboard'
    type:     annotation
    prefix:   /portal/dashboard
    trailing_slash_on_root: false

froq_basket:
    resource: '@FroqPortalBundle/Controller/AssetLibrary/Basket'
    type:     annotation
    prefix:   /portal/basket
    trailing_slash_on_root: false