froq_portal:
    resource: '@FroqPortalBundle/Controller/'
    type:     annotation
    prefix:   /portal
    trailing_slash_on_root: false

froq_portal_asset_library:
    resource: '@FroqPortalBundle/Controller/AssetLibrary/'
    type: annotation
    prefix: /portal/asset-library

froq_asset:
    resource: '@FroqAssetBundle/Controller/'
    type: annotation
    prefix: /

froq_portal_api:
    resource: '@FroqPortalBundle/Api/Controller/'
    type:     annotation
    prefix:   /portal/api
    trailing_slash_on_root: false

froq_portal_switch:
    resource: '@FroqAssetBundle/Switch/Controller/'
    type:     annotation
    prefix:   /switch
    trailing_slash_on_root: false

froq_portal_pimtoday:
    resource: '@FroqAssetBundle/PimToday/Controller/'
    type:     annotation
    prefix:   /pimtoday
    trailing_slash_on_root: false

froq_dashboard:
    resource: '@FroqPortalBundle/Controller/Dashboard'
    type:     annotation
    prefix:   /portal/dashboard
    trailing_slash_on_root: false