framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - Froq\AssetBundle\Messenger\AuditMiddleware
        transports:
            generate_asset_thumbnail:
                dsn: 'sync://'
                options: []
            switch_upload:
                dsn: 'sync://'
                options: []
            switch_upload_mailer:
                dsn: 'sync://'
                options: []
            youwe_es_indexing:
                dsn: 'sync://'
                options: []