monolog:
    handlers:
        streamed:
            type: rotating_file
            level: debug
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 10
            channels: ['!deprecation']
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: debug
            channels: [ "messenger_audit" ]