monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            formatter: monolog.formatter.line
            include_stacktraces: true
            channels: [ "!event" ]
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: debug
            channels: [ "messenger_audit" ]