pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    portal_asset_detail_preview:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 1000
                                    height: 800
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#FFFFFF'
                        medias: {  }
                        name: portal_asset_detail_preview
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1694066474
                        creationDate: 1689255269
                        preserveAnimation: false
