pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    portal_asset_library_item:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 160
                                    height: 160
                                    positioning: null
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#FFFFFF'
                        medias: {  }
                        name: portal_asset_library_item
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697715254
                        creationDate: 1683124978
                        preserveAnimation: false
