services:
    assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'https://s3.eu-central-1.amazonaws.com'
               region: 'eu-central-1'
               version: 'latest'
               credentials:
                   key: '%env(YOUWE_S3_STORAGE_KEY)%'
                   secret: '%env(YOUWE_S3_STORAGE_SECRET)%'

flysystem:
    storages:
        pimcore.thumbnail.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'thumbnails'
        pimcore.asset.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'assets'
        pimcore.asset_cache.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'asset-cache'
        pimcore.version.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'versions'
