services:
    assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 's3://froq-development-dam-assets-s3'
               region: 'eu-central-1'
               version: 'latest'

flysystem:
    storages:
        pimcore.thumbnail.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'thumbnails'
        pimcore.asset.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(AWS_S3_BUCKET_NAME_ASSETS)%'
                prefix: 'assets'
