framework:
    #### REDIS CACHE
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 259200 # 3 days
                adapter: pimcore.cache.adapter.redis_tag_aware
        default_redis_provider: '%env(REDIS_URL)%'

doctrine:
    dbal:
        connections:
            default:
                driver: pdo_mysql
                host: ##mysql_hostname##
                port: ##mysql_port##
                dbname: ##mysql_database##
                user: ##mysql_user##
                password: ##mysql_password##
                charset: UTF8MB4
                mapping_types:
                    enum: string
                    bit: boolean
                server_version: mariadb-10.6.7

youwe_pimcore_elasticsearch:
    es_hosts:
        - '%env(ES_URL)%'