framework:
    #### REDIS CACHE
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 15768000 # 6 months
                adapter: pimcore.cache.adapter.redis_tag_aware
        default_redis_provider: "redis://127.0.0.1:6379"

doctrine:
    dbal:
        connections:
            default:
                host: '%env(FROQ_DB_HOST)%'
                port: '%env(FROQ_DB_PORT)%'
                dbname: '%env(FROQ_DB_NAME)%'
                user: '%env(FROQ_DB_USER)%'
                password: '%env(FROQ_DB_PWD)%'
                charset: 'utf8mb4'
                mapping_types:
                    enum: string
                    bit: boolean
                server_version: '%env(FROQ_DB_VERSION)%'

youwe_pimcore_elasticsearch:
    es_hosts:
        - 'http://localhost:9200'