framework:
    cache:
        prefix_seed: '%kernel.environment%.pimcore.client-name'
    session:
        enabled: true
        cookie_secure: true
        cookie_samesite: lax
        cookie_lifetime: 15768000

doctrine:
    dbal:
        connections:
            default:
                host: '%env(FROQ_DB_HOST)%'
                port: '%env(FROQ_DB_PORT)%'
                dbname: '%env(FROQ_DB_NAME)%'
                user: '%env(FROQ_DB_USER)%'
                password: '%env(FROQ_DB_PWD)%'
                charset: 'utf8mb4'
                mapping_types:
                    enum: string
                    bit: boolean
                server_version: '%env(FROQ_DB_VERSION)%'

youwe_pimcore_elasticsearch:
    es_hosts:
        - 'http://localhost:9200'