_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

home:
    path: /
    controller: Froq\PortalBundle\Controller\HomeController::indexAction

download_page:
    path: /download-page/
    controller: Froq\PortalBundle\Controller\AssetLibrary\Basket\PublicPageController::downloadPage

download_public_file:
    path: /download-public-file/{id<\d+>}/{uuid}
    controller: Froq\PortalBundle\Controller\AssetLibrary\Basket\PublicPageController::downloadPublicFile

download_all_public_files:
    path: /download-all-public-files/
    controller: Froq\PortalBundle\Controller\AssetLibrary\Basket\PublicPageController::downloadAllPublicFiles