settings:
  number_of_replicas: 0
  number_of_shards: 5
  refresh_interval: 60s
  analysis:
    normalizer:
      keyword_norm:
        type: custom
        filter: [ "asciifolding", "lowercase" ]
    analyzer:
      text_analyzer:
        type: custom
        tokenizer: standard
        filter: [ "asciifolding", "lowercase" ]

mappings:
  dynamic: true
  properties:
    # Will be denormalized into ColourGuidelineItem DTO
    colourGuidelineId:
      type: integer
    name:
      type: keyword
    imageId:
      type: integer
    countries:
      type: keyword

    # Put all fields that needed to be searched, filtered, aggregated, filtered, sorted etc.
    created_at_timestamp:
      type: date
      format: 'yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis||epoch_second'
    updated_at_timestamp:
      type: date
      format: 'yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis||epoch_second'
    description:
      type: text

    # Aggregate Filters
    brands:
      type: keyword
    markets:
      type: keyword
    campaigns:
      type: keyword
    mediums:
      type: keyword
    substrates:
      type: keyword
    medium_types:
      type: keyword
    printing_techniques:
      type: keyword

    # Relations
    organization_id:
      type: integer
    organizations:
      type: keyword

    image_id:
      type: integer
    image_filename:
      type: keyword

    colour_ids:
      type: integer
    colour_names:
      type: keyword

    print_guidelines_ids:
      type: integer
    print_guidelines_names:
      type: keyword
    print_guidelines_descriptions:
      type: text